runtime: nodejs
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.2

resources:
  cpu: 0.2
  memory_gb: 0.2
  disk_size_gb: 10
